// react-todolist/src/App.tsx
import { useEffect, useState } from 'react';
import { TodoItem, TodoItemProps } from './components/TodoItem/TodoItem';
import {
  CustomRadio,
  StyledTodoItem,
} from './components/TodoItem/TodoItem.style';
import useTodos from './hooks/useTodos';
import './App.css';

type InputEventHandler = React.ChangeEventHandler<HTMLInputElement>;

function App() {
  const [searchValue, setSearchValue] = useState('');
  const [newTodoText, setNewTodoText] = useState('');
  const [mode, setMode] = useState<'input' | 'edit' | null>(null);
  const [todos, addTodo, updateTodo, deleteTodo] = useTodos();

  const searchedTodos = todos.filter((t) =>
    t.text.toLowerCase().includes(searchValue.toLowerCase())
  );

  const handleAddTodo: React.KeyboardEventHandler<HTMLInputElement> = (
    event
  ) => {
    if (event.key === 'Enter' && event.currentTarget.value) {
      addTodo(event.currentTarget.value);
      setNewTodoText('');
    }
  };

  const handleBlur = () => {
    setNewTodoText('');
    setMode(null);
  };

  const handleSearchChange: InputEventHandler = (event) => {
    setSearchValue(event.currentTarget.value);
  };

  const handleNewTodoTextChange: InputEventHandler = (event) => {
    setNewTodoText(event.currentTarget.value);
  };

  const handleUpdateTodo: TodoItemProps['onUpdateTodo'] = (
    todo,
    willReorder
  ) => {
    updateTodo(todo, willReorder);
  };

  const handleDeleteTodo: TodoItemProps['onDeleteTodo'] = (todo) => {
    if (todos.length === 1)
      return alert('Task list should have at least 1 task');
    deleteTodo(todo.id);
  };

  const handleToggleEdittingMode: TodoItemProps['onToggleEdittingMode'] = () =>
    setMode(mode === 'edit' ? null : 'edit');

  useEffect(() => {
    const onEnter = (event: KeyboardEvent) => {
      if (event.key === 'Enter' && mode === null) setMode('input');
    };

    window.addEventListener('keydown', onEnter);
    return () => window.removeEventListener('keydown', onEnter);
  });

  return (
    <section>
      <div className="alert">
        <img src="angular-logo.png" alt="React logo" width={50} />
        <p>
          Check out the Angular implementation here{' '}
          <a
            href="https://rintodolist.netlify.app/"
            target="_blank"
            rel="noopener noreferrer"
          >
            https://rintodolist.netlify.app/
          </a>
        </p>
      </div>

      <h2>
        React Todo List -{' '}
        <a href="https://github.com/thanhhoa214/learning/tree/main/react-todolist">
          Github
        </a>
      </h2>

      <input
        type="text"
        placeholder="Search"
        value={searchValue}
        onChange={handleSearchChange}
      />

      <ul>
        {searchedTodos.map((todo) => (
          <TodoItem
            key={todo.id}
            todo={todo}
            onDeleteTodo={handleDeleteTodo}
            onUpdateTodo={handleUpdateTodo}
            onToggleEdittingMode={handleToggleEdittingMode}
          />
        ))}

        {mode === 'input' && (
          <StyledTodoItem>
            <CustomRadio />
            <input
              autoFocus
              value={newTodoText}
              onChange={handleNewTodoTextChange}
              onKeyDown={handleAddTodo}
              onBlur={handleBlur}
            />
          </StyledTodoItem>
        )}
      </ul>
    </section>
  );
}

export default App;

// todolist/src/app/app.component.ts
import { Component, HostListener, computed, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';
import { TodoItem } from './model';
import { FormsModule } from '@angular/forms';

const idGeneratorFunc = () => {
  let index = 1;
  return () => {
    index++;
    return index;
  };
};
const idGenerator = idGeneratorFunc();

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
})
export class AppComponent {
  search = signal('');
  inputtingMode = false;
  inputValue = '';

  edittingId = -1;

  todos = signal<TodoItem[]>([
    { id: idGenerator(), status: 'pending', text: 'Task 1' },
    { id: idGenerator(), status: 'pending', text: 'Task 2' },
    { id: idGenerator(), status: 'completed', text: 'Task 8' },
  ]);

  filteredTodos = computed(() =>
    this.todos().filter((t) => t.text.toLowerCase().includes(this.search()))
  );

  @HostListener('document:keydown.enter')
  onHitEnter() {
    if (this.edittingId === -1) this.inputtingMode = true;
  }

  onChangeSearch(element: EventTarget | null) {
    if (!element) return;
    this.search.set((element as HTMLInputElement).value);
  }

  addTodo(text: string) {
    if (text === '') return;
    this.todos.set([
      ...this.todos(),
      { id: idGenerator(), status: 'pending', text },
    ]);
    this.inputValue = '';
  }

  editTodo(id: TodoItem['id']) {
    this.edittingId = id;
  }

  updateTodo(value: string, element: EventTarget | null) {
    const item = this.todos().find((t) => t.id === this.edittingId);
    if (!item || !element) return;

    item.text = value;
    this.todos.set(this.todos());
    (element as HTMLInputElement).blur();
    this.skipEdittingMode(element);
  }

  cancelEditting(element: EventTarget | null) {
    const item = this.todos().find((t) => t.id === this.edittingId);
    if (!item || !element) return;

    (element as HTMLInputElement).value = item.text;
    this.skipEdittingMode(element);
  }

  updateTodoStatus(id: TodoItem['id']) {
    const itemIndex = this.todos().findIndex((t) => t.id === id);
    if (itemIndex === -1) return;
    const [item] = this.todos().splice(itemIndex, 1);
    const isPending = item.status === 'pending';
    item.status = isPending ? 'completed' : 'pending';
    this.todos.set(
      isPending ? [...this.todos(), item] : [item, ...this.todos()]
    );
  }

  deleteTodo(id: TodoItem['id']) {
    if (this.todos().length === 1)
      return alert('Task list should have at least 1 task');
    this.todos.set(this.todos().filter((t) => t.id !== id));
  }

  private skipEdittingMode(element: EventTarget | null) {
    if (!element) return;
    (element as HTMLInputElement).blur();
    setTimeout(() => (this.edittingId = -1), 0);
  }
}

<div class="alert">
  <img src="assets/react-logo.png" alt="React logo" width="50" />
  <p>
    Check out the React implementation here
    <a
      href="https://reactrintodolist.netlify.app/"
      target="_blank"
      rel="noopener noreferrer"
    >
      https://reactrintodolist.netlify.app/
    </a>
  </p>
</div>

<h2>
  Todo List -
  <a href="https://github.com/thanhhoa214/learning/tree/main/todolist"
    >Github</a
  >
</h2>

<input
  type="text"
  placeholder="Search"
  [value]="search()"
  (input)="onChangeSearch($event.target)"
/>

<ul>
  <li *ngFor="let todo of filteredTodos()">
    <span
      class="custom-radio"
      [class.selected]="todo.status === 'completed'"
      (click)="inputRef.value !== '' ? updateTodoStatus(todo.id) : null"
    >
      <span>v</span>
    </span>
    <input
      #inputRef
      [value]="todo.text"
      class="editting-input"
      (click)="editTodo(todo.id)"
      (blur)="cancelEditting(inputRef)"
      (keydown.enter)="updateTodo(inputRef.value, inputRef)"
      (keydown.esc)="cancelEditting(inputRef)"
      (keydown.backspace)="inputRef.value === '' ? deleteTodo(todo.id) : null"
    />
  </li>

  <li *ngIf="inputtingMode">
    <span class="custom-radio"></span>
    <input
      type="text"
      [(ngModel)]="inputValue"
      autofocus
      (keydown.enter)="addTodo(inputValue)"
    />
  </li>
</ul>
